FROM nginx:1.24-alpine

WORKDIR /var/www/html

COPY . /var/www/html/
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY nginx.conf.sample /var/www/html/nginx.conf.sample

RUN mkdir -p /var/log/nginx /var/www/html && \
    chown -R nginx:nginx /var/www/html /var/log/nginx /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
