apiVersion: v1
kind: Service
metadata:
  name: magento-nginx
  namespace: magento2
spec:
  selector:
    app: magento-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
