# Dockerfile.db
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=pipe
ENV MYSQL_USER=pipe
ENV MYSQL_PASSWORD=1234

# Copy initialization SQL scripts if needed
# COPY ./init.sql /docker-entrypoint-initdb.d/

EXPOSE 3306

CMD ["mysqld"]
