# Dockerfile.db
FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=pipe
ENV MYSQL_USER=pipe
ENV MYSQL_PASSWORD=1234

# Copy initial dump only for first-time DB creation
COPY ./docker/db/init.sql /docker-entrypoint-initdb.d/init.sql

EXPOSE 3306

# FIXED: Use docker-entrypoint instead of "mysqld"
CMD ["docker-entrypoint.sh", "mysqld"]
